### ISSUE TITLE
Migrate Rosetta API to GRPCv2

### ISSUE THREAD

**Issue by rasmus-kirk** [Concordium/concordium-rosetta#51]
We need to migrate this API to use the GRPCv2 calls instead. The migration is implemented, and tested. Review is in process.

**Sub-tasks**
- [x] Change all GRPCv1 calls to GRPCv2
- [x] Get PR through review (#54) 
- [x] Update testing documentation in new PR (#55)

**Comment by abizjak** [comment]
I don't understand why this issue is closed. Where is the corresponding pull request that actually makes the changes?

**Comment by bisgardo** [comment]
Maybe it was replaced by https://github.com/Concordium/concordium-rosetta/issues/52?

**Comment by abizjak** [comment]
That's an epic. This is a task.
